version: '3'

networks:
  backend:
    driver: bridge

services:
  node:
    image: node:16.13.1
    container_name: node
    command: "npm start"
    networks:
      - backend
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    working_dir: "/home/node/app"